biomes:
  type: EXTRUSION
  extrusions:
    - << biome-providers/extrusions/add_cave_biomes.yml:extrusions
    - << biome-providers/extrusions/add_deep_dark.yml:extrusions
  provider:
    type: PIPELINE
    resolution: 4
    blend:
      amplitude: 2
      resolution: 2
      sampler:
        type: GAUSSIAN
    pipeline:

      # Caves Up to the Top of the World
      source: $biome-providers/sources/substratum.yml:source

      stages: 

        - << biome-providers/stages/expand.yml:stages
        - << biome-providers/stages/expand.yml:stages
        - << biome-providers/stages/smooth.yml:stages
        - << biome-providers/stages/smooth.yml:stages
        - << biome-providers/stages/smooth.yml:stages
        - << biome-providers/stages/expand.yml:stages
        - << biome-providers/stages/smooth.yml:stages
        - << biome-providers/stages/smooth.yml:stages
        - << biome-providers/stages/smooth.yml:stages

