id: BASE
type: BIOME
abstract: true
extends:
  - DEPOSITS_DEFAULT
  - ORES_DEFAULT

colors:
  fog: 0x000000
  sky: 0x000000

slant-depth: 15

features:
  global-preprocessors:
    - LAVA_FLOOR
    - UNDERGROUND_LAVA_COLUMNS
    - CAVE_GLOW_LICHEN
    - TEXTURED_STONE_SLANT



